# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e9c8b192bfbb8582313f562eb18873955ad0c4a7792260f60f93987c05b9e6e2735dadfef144bd4d7922562b7ca475230851d1350b580287fd1d95dddbdcc1d

test:
  secret_key_base: 115d18711690909aff907f450e855491aad568471672a19023d5d90ec91289d1d6821a9c82a94361f5990ca4b4da158852b15a36496711c5f135255ddeca95b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
